# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'bridge-agent:$(build.buildId)'
  dockerHubRegistry: mitquest

steps:
- task: Docker@1
  displayName: 'Login'
  inputs:
    command: login
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: mit-quest
- task: Docker@1
  displayName: 'Build'
  inputs:
    command: Build an image
    containerregistrytype: 'Container Registry'
    dockerFile: dockerfile
    imageName: $(imageName)
- task: Docker@1
  displayName: 'tag'
  inputs:
    command: Tag image
    containerregistrytype: Container Registry
    imageName: $(imageName)
    arguments: $(dockerHubRegistry)/$(imageName)
- task: Docker@1
  displayName: push
  inputs:
    command: Push an image
    containerregistrytype: Container Registry
    dockerRegistryEndpoint: mit-quest
    imageName: $(dockerHubRegistry)/$(imageName)
