kind: Secret
apiVersion: v1
metadata:
  name: {{ include "bridge-agent.fullname" . }}
  labels:
    app: {{ include "bridge-agent.name" . }}
    chart: {{ include "bridge-agent.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.service }}
type: Opaque
data:
  vsts.accessToken: {{ required "VSTS Access Token: .Values.secrets.agentPoolAccessToken required!" .Values.secrets.agentPoolAccessToken | b64enc }}
  {{- if .Values.gcp }}
  {{- $file := required "GCP Service Account Key: .Values.secrets.gcpServiceAccountKeyfile required!" .Values.secrets.gcpServiceAccountKeyfile }}
  gcp.serviceAccountKey: {{ .Files.Get $file | b64enc }}
  {{- end}}
