kind: Secret
apiVersion: v1
metadata:
  name: {{ include "bridge-agent.fullname" . }}
  labels:
    app: {{ include "bridge-agent.name" . }}
    chart: {{ include "bridge-agent.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.service }}
type: Opaque
data:
  accessToken: {{ required "VSTS Access Token: .Values.secrets.accessToken required!" .Values.secrets.accessToken | b64enc }}
